services:
    main:
        image: ghcr.io/plfanzen/demo-chal:main
        ports:
            - name: web
              target: 22
              protocol: tcp
              app_protocol: ssh
              x-username: plfanzen
              x-password: plfanzy

x-ctf-metadata:
    name: SSH Test
    description_md: |
        Just testing SSH stuff.
    difficulty: "easy"
    base_points: 100
    categories:
        - misc
    authors:
        - Aaron
        - Plfanzen
    flag: PLFANZEN{TEST_SSH}
